name: Firebase Continuous Deployment

on:
  push:
    branches: [ master ]


jobs:
  deploy:
    name: Deploy Application on pushing new code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.3
      - name: Setup Node Environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.13.0
      - name: Clean Install NPM Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Firebase Deploy
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}