name: Firebase Continuous Deployment

on:
  push:
    branches: [ master ]


jobs:
  build:
    name: Build on Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.3
      - name: Setup Node Environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.13.0
      - name: Clean Install NPM Dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public
        
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.3
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public
      - name: Firebase Deploy
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}