name: Node Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  test_pull_request:
    name: Testing Application on Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.3
      - name: Setup Node Environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14.13.0
      - name: Clean Install NPM Dependencies
        run: npm ci
      - name: Run Testing of Application
        run: npm test
      - name: Build project
        run: npm run build
